ALTER TABLE users ADD COLUMN first_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN last_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN age INTEGER NOT NULL DEFAULT 18;
ALTER TABLE users ADD COLUMN gender TEXT NOT NULL DEFAULT 'other';
